version: '3.4'

services:
  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd"
      MSSQL_PID: "Express"
      MSSQL_RPC_PORT: 135
      MSSQL_DTC_TCP_PORT: 51000
    container_name: sql_express
    ports:
      - "1433:1433"
      - "135:135"
      - "51000:51000"